# events but only for the master branch
on:
  push:
    branches: [ master ]
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    #- name: docker build .netapp
     # run: |
      #  docker build ./home/runner/work/ -t verzioni1
        
    - name: Palidhje Name qetu
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: whoami
