# events but only for the master branch
on:
  push:
    branches: [ master ]
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testingssh    
      uses: appleboy/ssh-action@master
      with:
        host: 88.198.172.204
        username: root
        key: ${{ secrets.DOCKER_PASSWORD}}
        port: 22
        script: |
           cd Uploadfile
           git pull origin master
         

