# events but only for the master branch
on:
  push:
    branches: [ master ]
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dotnet Setup-i
      uses: action/setup-dotnet@v1
      with:
         dotnet-verzion: 3.1
    - name: DotnetPublish 
      run: dotnet publish src -c Release -o Uploadfile
    
        
    - name: Palidhje Name qetu
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          port: 22
          script: |
           cd ~/Documents
           
           #- name: docker build .netapp
    #  run: |
     #   docker build . -t verzioni1
            
