# events but only for the master branch
on:
  push:
    branches: [ master ]
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
     - name: Copying files to server
       uses: appleboy/scp-action@master
       with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}

          scripts: |
           cd Uploadfile
           git pull origin master
           
         

